import { CommonModule } from '@angular/common';
import { Meta, moduleMetadata, Story } from '@storybook/angular';
import { WeekRowComponent } from '../app/components/week-row/week-row.component';
import { DayCardComponent } from '../app/components/day-card/day-card.component';
import { CalendarComponent } from 'src/app/components/calendar/calendar.component';
import { CalendarHeaderTitleComponent } from 'src/app/components/calendar-header-title/calendar-header-title.component';
import { CalendarHeaderComponent } from 'src/app/components/calendar-header/calendar-header.component';
import { DayHeaderComponent } from 'src/app/components/day-header/day-header.component';
import { AddActivityButtonComponent } from 'src/app/components/add-activity-button/add-activity-button.component';
import { CardFooterHiddenItemsComponent } from 'src/app/components/card-footer-hidden-items/card-footer-hidden-items.component';
import { CardFooterHoursComponent } from 'src/app/components/card-footer-hours/card-footer-hours.component';
import { CardFooterComponent } from 'src/app/components/card-footer/card-footer.component';
import { ItemDiaComponent } from 'src/app/components/item-dia/item-dia.component';
import { ListaDiaComponent } from 'src/app/components/lista-dia/lista-dia.component';
import { NumberDayComponent } from 'src/app/components/number-day/number-day.component';
import { PopoverBodyTextComponent } from 'src/app/components/popover-body-text/popover-body-text.component';
import { PopoverBodyComponent } from 'src/app/components/popover-body/popover-body.component';
import { PopoverButtonComponent } from 'src/app/components/popover-button/popover-button.component';
import { PopoverListFooterComponent } from 'src/app/components/popover-list-footer/popover-list-footer.component';
import { PopoverComponent } from 'src/app/components/popover/popover.component';
import { TooltipCalendarComponent } from 'src/app/components/tooltip-calendar/tooltip-calendar.component';
import { WarningDayComponent } from 'src/app/components/warning-day/warning-day.component';
import { PItemDiaComponent } from 'src/app/components/p-item-dia/p-item-dia.component';
import { screen, userEvent } from '@storybook/testing-library';

export default {
  title: 'Calendar/Calendar',
  component: CalendarComponent,
  decorators: [
    moduleMetadata({
      declarations: [
        WeekRowComponent,
        DayCardComponent,
        CalendarHeaderComponent,
        CalendarHeaderTitleComponent,
        ListaDiaComponent,
        PItemDiaComponent,
        DayHeaderComponent,
        CardFooterComponent,
        CardFooterHoursComponent,
        CardFooterHiddenItemsComponent,
        WarningDayComponent,
        NumberDayComponent,
        TooltipCalendarComponent,
        AddActivityButtonComponent,
        ListaDiaComponent,
        ItemDiaComponent,
        PopoverBodyComponent,
        PopoverBodyTextComponent,
        PopoverButtonComponent,
        PopoverListFooterComponent,
        PopoverComponent,
        PopoverComponent,
        PopoverBodyComponent,
        PopoverBodyTextComponent,
        CardFooterHoursComponent,
        PopoverButtonComponent,
        PopoverListFooterComponent,
      ],
      imports: [CommonModule],
    }),
  ],
} as Meta;

const Template: Story<CalendarComponent> = (args: CalendarComponent) => ({
  props: args,
});

export const Calendar = Template.bind({});
Calendar.play =async () => {
  const button = screen.getByTestId('item-dia')
  await userEvent.hover(button)
}
Calendar.args = {
  monthArr: 
    [
      {
        day: 1,
        activities: [
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
        ],
        date: new Date()
      },
      {
        day: 2,
        activities: [
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
        ],
        date: new Date()
      },
      {
        day: 3,
        activities: [
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
        ],
        date: new Date()
      },
      {
        day: 4,
        activities: [
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
        ],
        date: new Date()
      },
      {
        day: 5,
        activities: [
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
        ],
        date: new Date()
      },
      {
        day: 6,
        activities: [
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
        ],
        date: new Date()
      },
      {
        day: 7,
        activities: [
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
        ],
        date: new Date()
      },
      {
        day: 8,
        activities: [
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
        ],
        date: new Date()
      },
      {
        day: 9,
        activities: [
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
        ],
        date: new Date()
      },
      {
        day: 10,
        activities: [
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
        ],
        date: new Date()
      },
      {
        day: 11,
        activities: [
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
        ],
        date: new Date()
      },
      {
        day: 12,
        activities: [
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
        ],
        date: new Date()
      },
      {
        day: 13,
        activities: [
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
        ],
        date: new Date()
      },
      {
        day: 14,
        activities: [
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
        ],
        date: new Date()
      },
      {
        day: 15,
        activities: [
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
        ],
        date: new Date()
      },
      {
        day: 16,
        activities: [
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
        ],
        date: new Date()
      },
      {
        day: 17,
        activities: [
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
        ],
        date: new Date()
      },
      {
        day: 18,
        activities: [
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
        ],
        date: new Date()
      },
      {
        day: 19,
        activities: [
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
        ],
        date: new Date()
      },
      {
        day: 20,
        activities: [
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
        ],
        date: new Date()
      },
      {
        day: 21,
        activities: [
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
        ],
        date: new Date()
      },
      {
        day: 22,
        activities: [
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
        ],
        date: new Date()
      },
      {
        day: 23,
        activities: [
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
        ],
        date: new Date()
      },
      {
        day: 24,
        activities: [
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
        ],
        date: new Date()
      },
      {
        day: 25,
        activities: [
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
        ],
        date: new Date()
      },
      {
        day: 26,
        activities: [
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
        ],
        date: new Date()
      },
      {
        day: 27,
        activities: [
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
        ],
        date: new Date()
      },
      {
        day: 28,
        activities: [
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
        ],
        date: new Date()
      },
      {
        day: 29,
        activities: [
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
        ],
        date: new Date()
      },
      {
        day: 30,
        activities: [
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
        ],
        date: new Date()
      },
      {
        day: 31,
        activities: [
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
          {
            AccountName: 'Itexico',
            ActivityDate: '2022-05-06T09:35:04',
            ActivityID: 0,
            CategoryName: 'Available',
            Comments: 'string',
            EmployeeID: 0,
            ProjectColor: 'blue',
            ProjectID: 0,
            ProjectName: 'Delivery',
            StepID: 0,
            Task: 'esto es un ticket',
            TypeID: 0,
            value: 5,
            activeInProject: false,
          },
        ],
        date: new Date()
      },
      {},
      {},
      {},
      {},
    ],
};
