import { Component, Input, OnInit } from '@angular/core';
import { Activity } from '../../services/data-service/data-interfaces';
interface Day{
  weeklyDay?: string | undefined,
  numberDay?: number | undefined,
}
interface Card{
  day: Day | undefined
  activities: Activity[]
}
@Component({
  selector: 'app-week-row',
  templateUrl: './week-row.component.html',
  styleUrls: ['./week-row.component.scss'],
})
export class WeekRowComponent implements OnInit {
  @Input() cards: Card[] = [
    // {
    //   day: {},
    //   activities: [],
    // },
    // {
    //   day: {},
    //   activities: [],
    // },
    // {
    //   day: {
    //     weeklyDay: 'Monday',
    //     numberDay: 1,
    //   },
    //   activities: [
    //   ],
    // },
    // {
    //   day: {
    //     weeklyDay: 'Monday',
    //     numberDay: 2,
    //   },
    //   activities: [
    //     {
    //       AccountName: 'Itexico ',
    //       ActivityDate: '2011-12-19T15:28:46.493Z',
    //       ActivityID: 0,
    //       CategoryName: 'Avalaible',
    //       Comments: 'Comentario de las actividades realizadas',
    //       EmployeeID: 0,
    //       ProjectColor: 'blue',
    //       ProjectID: 0,
    //       ProjectName: 'Delivery',
    //       StepID: 0,
    //       Task: 'Este es un ticket',
    //       TypeID: 0,
    //       value: 8,
    //       activeInProject: false,
    //     },
    //     {
    //       AccountName: 'Itexico ',
    //       ActivityDate: '2011-12-19T15:28:46.493Z',
    //       ActivityID: 0,
    //       CategoryName: 'Avalaible',
    //       Comments: 'Comentario de las actividades realizadas',
    //       EmployeeID: 0,
    //       ProjectColor: 'blue',
    //       ProjectID: 0,
    //       ProjectName: 'Delivery',
    //       StepID: 0,
    //       Task: 'Este es un ticket',
    //       TypeID: 0,
    //       value: 8,
    //       activeInProject: false,
    //     },
    //     {
    //       AccountName: 'Itexico ',
    //       ActivityDate: '2011-12-19T15:28:46.493Z',
    //       ActivityID: 0,
    //       CategoryName: 'Avalaible',
    //       Comments: 'Comentario de las actividades realizadas',
    //       EmployeeID: 0,
    //       ProjectColor: 'blue',
    //       ProjectID: 0,
    //       ProjectName: 'Delivery',
    //       StepID: 0,
    //       Task: 'Este es un ticket',
    //       TypeID: 0,
    //       value: 8,
    //       activeInProject: false,
    //     },
    //   ],
    // },
    // {
    //   day: {
    //     weeklyDay: 'Monday',
    //     numberDay: 3,
    //   },
    //   activities: [
    //     {
    //       AccountName: 'Itexico ',
    //       ActivityDate: '2011-12-19T15:28:46.493Z',
    //       ActivityID: 0,
    //       CategoryName: 'Avalaible',
    //       Comments: 'Comentario de las actividades realizadas',
    //       EmployeeID: 0,
    //       ProjectColor: 'blue',
    //       ProjectID: 0,
    //       ProjectName: 'Delivery',
    //       StepID: 0,
    //       Task: 'Este es un ticket',
    //       TypeID: 0,
    //       value: 8,
    //       activeInProject: false,
    //     },
    //     {
    //       AccountName: 'Itexico ',
    //       ActivityDate: '2011-12-19T15:28:46.493Z',
    //       ActivityID: 0,
    //       CategoryName: 'Avalaible',
    //       Comments: 'Comentario de las actividades realizadas',
    //       EmployeeID: 0,
    //       ProjectColor: 'blue',
    //       ProjectID: 0,
    //       ProjectName: 'Delivery',
    //       StepID: 0,
    //       Task: 'Este es un ticket',
    //       TypeID: 0,
    //       value: 8,
    //       activeInProject: false,
    //     },
    //     {
    //       AccountName: 'Itexico ',
    //       ActivityDate: '2011-12-19T15:28:46.493Z',
    //       ActivityID: 0,
    //       CategoryName: 'Avalaible',
    //       Comments: 'Comentario de las actividades realizadas',
    //       EmployeeID: 0,
    //       ProjectColor: 'blue',
    //       ProjectID: 0,
    //       ProjectName: 'Delivery',
    //       StepID: 0,
    //       Task: 'Este es un ticket',
    //       TypeID: 0,
    //       value: 8,
    //       activeInProject: false,
    //     },
    //   ],
    // },
    // {
    //   day: {
    //     weeklyDay: 'Monday',
    //     numberDay: 4,
    //   },
    //   activities: [
    //     {
    //       AccountName: 'Itexico ',
    //       ActivityDate: '2011-12-19T15:28:46.493Z',
    //       ActivityID: 0,
    //       CategoryName: 'Avalaible',
    //       Comments: 'Comentario de las actividades realizadas',
    //       EmployeeID: 0,
    //       ProjectColor: 'blue',
    //       ProjectID: 0,
    //       ProjectName: 'Delivery',
    //       StepID: 0,
    //       Task: 'Este es un ticket',
    //       TypeID: 0,
    //       value: 8,
    //       activeInProject: false,
    //     },
    //     {
    //       AccountName: 'Itexico ',
    //       ActivityDate: '2011-12-19T15:28:46.493Z',
    //       ActivityID: 0,
    //       CategoryName: 'Avalaible',
    //       Comments: 'Comentario de las actividades realizadas',
    //       EmployeeID: 0,
    //       ProjectColor: 'blue',
    //       ProjectID: 0,
    //       ProjectName: 'Delivery',
    //       StepID: 0,
    //       Task: 'Este es un ticket',
    //       TypeID: 0,
    //       value: 8,
    //       activeInProject: false,
    //     },
    //     {
    //       AccountName: 'Itexico ',
    //       ActivityDate: '2011-12-19T15:28:46.493Z',
    //       ActivityID: 0,
    //       CategoryName: 'Avalaible',
    //       Comments: 'Comentario de las actividades realizadas',
    //       EmployeeID: 0,
    //       ProjectColor: 'blue',
    //       ProjectID: 0,
    //       ProjectName: 'Delivery',
    //       StepID: 0,
    //       Task: 'Este es un ticket',
    //       TypeID: 0,
    //       value: 8,
    //       activeInProject: false,
    //     },
    //   ],
    // },
    // {
    //   day: {
    //     weeklyDay: 'Monday',
    //     numberDay: 5,
    //   },
    //   activities: [
    //     {
    //       AccountName: 'Itexico ',
    //       ActivityDate: '2011-12-19T15:28:46.493Z',
    //       ActivityID: 0,
    //       CategoryName: 'Avalaible',
    //       Comments: 'Comentario de las actividades realizadas',
    //       EmployeeID: 0,
    //       ProjectColor: 'blue',
    //       ProjectID: 0,
    //       ProjectName: 'Delivery',
    //       StepID: 0,
    //       Task: 'Este es un ticket',
    //       TypeID: 0,
    //       value: 8,
    //       activeInProject: false,
    //     },
    //     {
    //       AccountName: 'Itexico ',
    //       ActivityDate: '2011-12-19T15:28:46.493Z',
    //       ActivityID: 0,
    //       CategoryName: 'Avalaible',
    //       Comments: 'Comentario de las actividades realizadas',
    //       EmployeeID: 0,
    //       ProjectColor: 'blue',
    //       ProjectID: 0,
    //       ProjectName: 'Delivery',
    //       StepID: 0,
    //       Task: 'Este es un ticket',
    //       TypeID: 0,
    //       value: 8,
    //       activeInProject: false,
    //     },
    //     {
    //       AccountName: 'Itexico ',
    //       ActivityDate: '2011-12-19T15:28:46.493Z',
    //       ActivityID: 0,
    //       CategoryName: 'Avalaible',
    //       Comments: 'Comentario de las actividades realizadas',
    //       EmployeeID: 0,
    //       ProjectColor: 'blue',
    //       ProjectID: 0,
    //       ProjectName: 'Delivery',
    //       StepID: 0,
    //       Task: 'Este es un ticket',
    //       TypeID: 0,
    //       value: 8,
    //       activeInProject: false,
    //     },
    //   ],
    // },
  ];

  constructor() {}

  ngOnInit(): void {}
}
